apiVersion: v1
kind: Template
metadata:
  name: varnish
  annotations:
    description: "Varnish Cache is a web application accelerator also known as a caching HTTP reverse proxy." 
    tags: "load balancer, cache, varnish" 
labels:      
  template: varnish
  group: varnish
  version: 1.0.0
objects:   
- kind: Service
  apiVersion: v1
  metadata:
    name: varnish-front
  spec:
    selector:
      name: varnish-front
    ports:
    - name: varnish
      protocol: TCP
      port: 80
      targetPort: 6081
      nodePort: 0
    portalIP: ''
    type: ClusterIP
- kind: Service
  apiVersion: v1
  metadata:
    name: varnish-admin
  spec:
    selector: 
      name: varnish-admin
    ports:
    - name: varnish-admin
      protocol: TCP
      port: 6082
      targetPort: 6082
      nodePort: 0
    portalIP: ''
    type: ClusterIP
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: varnish
  spec:
    dockerImageRepository: koscicz/varnish
    tags:
    - name: latest
- kind: Route
  apiVersion: v1
  metadata:
    name: varnish-front-route
  spec:
    host: ''
    to:
      kind: Service
      name: varnish-front
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: varnish
  spec:
    selector:
      name: varnish-front
    strategy:
      type: Rolling
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - varnish
        from:
          kind: ImageStreamTag
          name: varnish:latest
    replicas: 1
    template:
      metadata:
        name: varnish-dummy
        labels:
          name: varnish-front
      spec:
        containers:
        - name: varnish
          image: varnish:latest
          ports:
          - containerPort: 6081
